# Generated by Django 2.0.3 on 2019-04-03 11:36

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20190402_1242'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='artile_image',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Makale Fotoğrafı'),
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=ckeditor.fields.RichTextField(verbose_name='İçerik'),
        ),
    ]
