# Generated by Django 2.0.3 on 2019-04-03 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_auto_20190403_1436'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='artile_image',
            new_name='article_image',
        ),
    ]
